name: CI dev

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build et save
        run: |
          docker build -t tidianesar09/intranet-newdeal:${{ github.sha }} -t tidianesar09/intranet-newdeal:latest .
          docker save tidianesar09/intranet-newdeal:${{ github
