name: CI Évolué – Slim, CRITICAL Block & Email (dev)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  IMAGE_NAME: tidianesar09/intranet-newdeal
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build:
   - name: Build de l'image Docker
        env:
          IMG: tidianesar09/intranet-newdeal
          TAG: ${{ github.sha }}
        run: |
          docker build --tag $IMG:$TAG --tag $IMG:latest .
